### ISSUE TITLE
ANDROID: Task :@react-native-community_datetimepicker:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by rashtay** [react-native-community/react-native-datetimepicker#11] opened 2019-07-22 07:08 UTC
# Bug

> Task :@react-native-community_datetimepicker:compileDebugJavaWithJavac FAILED
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:24: error: package androidx.fragment.app does not exist
import androidx.fragment.app.DialogFragment;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:28: error: cannot find symbol
public class RNDatePickerDialogFragment extends DialogFragment {
                                                ^
  symbol: class DialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java:14: error: package androidx.fragment.app does not exist
import androidx.fragment.app.FragmentActivity;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java:15: error: package androidx.fragment.app does not exist
import androidx.fragment.app.FragmentManager;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:18: error: package androidx.fragment.app does not exist
import androidx.fragment.app.DialogFragment;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:27: error: cannot find symbol
public class RNTimePickerDialogFragment extends DialogFragment {
                                                ^
  symbol: class DialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:14: error: package androidx.fragment.app does not exist
import androidx.fragment.app.DialogFragment;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:15: error: package androidx.fragment.app does not exist
import androidx.fragment.app.FragmentActivity;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:16: error: package androidx.fragment.app does not exist
import androidx.fragment.app.FragmentManager;
                            ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:36: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:38: error: cannot find symbol
    Bundle args = getArguments();
                  ^
  symbol:   method getArguments()
  location: class RNDatePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:39: error: cannot find symbol
    instance = createDialog(args, getActivity(), mOnDateSetListener);
                                  ^
  symbol:   method getActivity()
  location: class RNDatePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:122: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java:124: error: cannot find symbol
    super.onDismiss(dialog);
    ^
  symbol:   variable super
  location: class RNDatePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java:104: error: cannot find symbol
    FragmentActivity activity = (FragmentActivity) getCurrentActivity();
    ^
  symbol:   class FragmentActivity
  location: class RNDatePickerDialogModule
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java:104: error: cannot find symbol
    FragmentActivity activity = (FragmentActivity) getCurrentActivity();
                                 ^
  symbol:   class FragmentActivity
  location: class RNDatePickerDialogModule
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java:112: error: cannot find symbol
    FragmentManager fragmentManager = activity.getSupportFragmentManager();
    ^
  symbol:   class FragmentManager
  location: class RNDatePickerDialogModule
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogModule.java:129: error: cannot find symbol
      fragment.setArguments(createFragmentArguments(options));
              ^
  symbol:   method setArguments(Bundle)
  location: variable fragment of type RNDatePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:35: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:37: error: cannot find symbol
    final Bundle args = getArguments();
                        ^
  symbol:   method getArguments()
  location: class RNTimePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:38: error: cannot find symbol
    instance = createDialog(args, getActivity(), mOnTimeSetListener);
                                  ^
  symbol:   method getActivity()
  location: class RNTimePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:100: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogFragment.java:102: error: cannot find symbol
    super.onDismiss(dialog);
    ^
  symbol:   variable super
  location: class RNTimePickerDialogFragment
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:78: error: cannot find symbol
    FragmentActivity activity = (FragmentActivity) getCurrentActivity();
    ^
  symbol:   class FragmentActivity
  location: class RNTimePickerDialogModule
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:78: error: cannot find symbol
    FragmentActivity activity = (FragmentActivity) getCurrentActivity();
                                 ^
  symbol:   class FragmentActivity
  location: class RNTimePickerDialogModule
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:87: error: cannot find symbol
    FragmentManager fragmentManager = activity.getSupportFragmentManager();
    ^
  symbol:   class FragmentManager
  location: class RNTimePickerDialogModule
/Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java:104: error: cannot find symbol
      fragment.setArguments(createFragmentArguments(options));
              ^
  symbol:   method setArguments(Bundle)
  location: variable fragment of type RNTimePickerDialogFragment
Note: /Users/rahshett/localshiva/QuickCare/node_modules/@react-native-community/datetimepicker/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
27 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-community_datetimepicker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 11s
19 actionable tasks: 11 executed, 8 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: ./gradlew app:installDebug. Run CLI with --verbose flag for more details.

## Environment info
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 273.63 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: ^0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: ^1.0.0

## Steps To Reproduce

1. npm i @react-native-community/datetimepicker
2. npm link @react-native-community/datetimepicker
3. react-native run-android
...

Describe what you expected to happen:

1. App to install successfully in the Emulator

**Comment by Swaagie** [comment] 2019-07-31 14:12
@rashtay thanks for reporting. What version of Gradle did you use to build your app?

In an ideal world the components do not use any deprecated API methods, but I'm not that intimate with the development of the language itself to know first hand what replaces each method. 

Most of this code has been directly ported from the code base of React Native itself. Hence I wonder if there is a version discrepancy here. I'll try to reproduce first local. It might just be the 0.60 upgrade, for which there is work in progress, see https://github.com/react-native-community/react-native-datetimepicker/pull/13

**Comment by rashtay** [comment] 2019-08-06 07:15
> @rashtay thanks for reporting. What version of Gradle did you use to build your app?
> 
> In an ideal world the components do not use any deprecated API methods, but I'm not that intimate with the development of the language itself to know first hand what replaces each method.
> 
> Most of this code has been directly ported from the code base of React Native itself. Hence I wonder if there is a version discrepancy here. I'll try to reproduce the first local. It might just be the 0.60 upgrades, for which there is work in progress, see #13

@Swaagie com.android.tools.build:gradle:3.4.2

I hope this helps. Do let me know if you need clarity on anything else.

**Comment by Swaagie** [comment] 2019-08-13 08:21
@rashtay I've just published `@react-native-community/datetimepicker@2.0.0` which works against React Native 0.60, let me know if that resolves your build issues.

**Comment by rashtay** [comment] 2019-08-14 12:20
@Swaagie Works. Thanks a lot :)

**Comment by QuintonC** [comment] 2019-09-06 14:21
@Swaagie @2.0.0 is not working for me. I'm getting the same issue as above.

![Screen Shot 2019-09-06 at 10 20 17 AM](https://user-images.githubusercontent.com/4250423/64435164-ff155680-d08f-11e9-944c-a45dcc194bd1.png)

**Comment by arslanrazzaq** [comment] 2019-09-13 10:42
@Swaagie i try to use the ^2.0.0 version but i'm getting same error as @rashtay .

**Comment by wasim-abuzaher** [comment] 2019-09-16 20:21
Facing same issue, using v^2.0.0 and `"react-native": "0.59.5"`

```* What went wrong:
Execution failed for task ':react-native-datetimepicker:compileDebugJavaWithJavac'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0
```

**Comment by skurgansky-sugarcrm** [comment] 2019-09-30 13:50
Do your android detox tests work ?
I tried and it failed. I was wondering how you managed to setup detox skipping build integration and it supposed to work. Looks like not.

**Comment by suhask-iprogrammer** [comment] 2019-11-01 12:41
@Swaagie  Facing same issue, using v^2.0.0 
"react-native": "0.59.5"
"Gradle": 3.4.1

Error: Task: react-native-datetimepicker:compileDebugJavaWithJavac FAILED

**Comment by ventr1x** [comment] 2019-11-25 12:23
Another broken plugin it seems. Same issue, no chance to compile the app with gradle

**Comment by hardywu** [comment] 2019-12-12 19:56
Facing same issue. Thought tt works on IOS.

**Comment by mrriyous** [comment] 2019-12-17 11:11
Facing same issue. Is there any solutions for this ?

**Comment by swalahamani** [comment] 2019-12-26 06:31
Same issue. Any work around?

**Comment by eightyfive** [comment] 2020-01-06 13:56
[RNDatePickerDialogFragment.java](https://github.com/react-native-community/react-native-datetimepicker/blob/2.1.0/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDatePickerDialogFragment.java) is trying to import from AndroidX:
```java
import androidx.fragment.app.DialogFragment;
```

So it seems like [react-native-datetimepicker](https://github.com/react-native-community/react-native-datetimepicker) does not support `react-native < 0.60` ??

**Comment by mikehardy** [comment] 2020-01-06 14:11
@eightyfive jetifier in -r mode should work though, yes? 

https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries

**Comment by eightyfive** [comment] 2020-01-06 14:15
I had no idea this existed. I'll give it a try. Thanks @mikehardy.

**Comment by AbdelkhalekESI** [comment] 2020-01-09 03:08
Try to migrate to AndroidX

**Comment by jvgaeta** [comment] 2020-01-16 00:58
@mikehardy Thanks for the tip! Got it working by doing:

1. rm -rf node_modules
2. npm install
3. npx jetify -r
4. npm run android:build

**Comment by mikehardy** [comment] 2020-01-16 01:53
Great to hear that works! Note that I am a huge proponent of moving to AndroidX + react-native 0.60. It is painful. But the auto-linking stuff and cocoapods, they do justify the pain. In the meantime, understanding the pain, I'll keep jetifier working (forwards and backwards) so we can all get work done. Cheers

**Comment by jvgaeta** [comment] 2020-01-16 02:06
@mikehardy We will definitely migrate shortly. We developed on expokit, which turned out to be a mistake and will be migrating off of that as well since it prevents us from upgrading to the newest RN version. We're just too close to launch right now to do any major migrations. Thanks again!

**Comment by vonovak** [comment] 2020-01-30 22:10
closing, please use the solution from https://github.com/react-native-community/react-native-datetimepicker/issues/11#issuecomment-574929166 or upgrade to RN >= 0.60

**Closed by vonovak** 2020-01-30 22:10 UTC
Labels: bug, help wanted
