### ISSUE TITLE
display="spinner" not work

### ISSUE THREAD

**Issue by robertototti** [react-native-community/react-native-datetimepicker#76] opened 2019-12-31 10:55 UTC
# Bug

on apk DateTimePicker show like display default but i need like spinner

## Environment info

React native info output:

```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - lottie-react-native: https://github.com/airbnb/lottie-react-native#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
info Fetching system and libraries information...
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 780.99 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/opt/node@12/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-26 | Android TV Intel x86 Atom, android-26 | China version of Android Wear Intel x86 Atom, android-26 | Android Wear Intel x86 Atom, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Android TV Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | China version of Wear OS Intel x86 Atom, android-28 | Wear OS Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-Q | Android TV Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
```

Library version: "@react-native-community/datetimepicker": "^2.1.0"

this is how i use: 
```
{(visible && Platform.OS !== 'ios') ?
        <RNDateTimePicker display="spinner" value={date} onChange={onChange} minimumDate={minDate}
                        maximumDate={maxiDate}/> : null}
```
or:
```
<DateTimePicker display="spinner" value={date} onChange={onChange} minimumDate={minDate}
                        maximumDate={maxDate}/> : null}
```
in development mode, when i use expo-client, all is well and I see DateTimePicker like spinner display.
but when i build project on apk I see DateTimePicker like default display. what i do wrong?

**Comment by GerardoStella** [comment] 2020-01-07 15:29
I'm having the same issue

**Comment by lateshK** [comment] 2020-01-09 09:41
+1

**Comment by pachaval** [comment] 2020-01-09 13:26
+1

**Comment by rodrieja** [comment] 2020-01-09 14:40
I'm having the same issue.

**Comment by lucasgozzi** [comment] 2020-01-31 17:41
me 2

**Comment by luancurti** [comment] 2020-02-01 21:45
This PR #47 fix this bug. Guys we can test again with the version `2.1.2` ? I think this issue could be closed @vonovak

**Comment by petestewartnz** [comment] 2020-02-04 19:02
I also have this issue on version 2.1.1

**Comment by luancurti** [comment] 2020-02-05 03:33
@petestewartnz the fix is in the version `2.1.2` could you update to this version and test again?

**Comment by petestewartnz** [comment] 2020-02-05 04:06
> @petestewartnz the fix is in the version `2.1.2` could you update to this version and test again?

I am updated to 2.2.1 and still the same issue.

**Comment by vonovak** [comment] 2020-02-05 09:25
@petestewartnz please add a runnable reproduction and details on what platform / device is affected, otherwise this is not actionable and will be closed. see https://stackoverflow.com/help/minimal-reproducible-example

**Comment by gabrielnaoto** [comment] 2020-02-05 21:50
I'm also having this issue.  :/

**Comment by gabrielnaoto** [comment] 2020-02-06 12:53
For what I could tell, I've cloned the project into local, and ran the example project, and only the spinner works. If I try to change the display to calendar, it does not work :/

In my project it happens exactly the opposite, it's displayed as a calendar and I can't change it to spinner mode.

![image](https://user-images.githubusercontent.com/13211186/73938629-6dbc4180-48c6-11ea-8d08-a60cd625b25e.png)

Sidenote: My project runs in Expo (don't know if that matters)

**Comment by luancurti** [comment] 2020-02-10 00:24
@gabrielnaoto Can you test again using my branch https://github.com/luancurti/react-native-datetimepicker/tree/chore/add-spinner-mode-example ? I updated the example using date picker with `display="spinner"` using `Android Emulator 7.1.1` (this problem occurs only in Android Nougat `7.1.1`) I've tested and everything work as expected, thanks!

**Comment by thanh90** [comment] 2020-02-12 08:40
in my project, I set to 'spinner' bit it shows 'clock'

**Comment by luancurti** [comment] 2020-02-14 12:01
I'll close this issues because doesn't have a reproducible demo, feel free to open another issue with a reproducible demk

**Closed by luancurti** 2020-02-14 12:01 UTC
