### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

### ISSUE THREAD

**Issue by dmargu** [react-native-community/react-native-datetimepicker#12] opened 2019-07-25 19:45 UTC
# Bug

  The component appears to not be working. Once my app reaches the screen where the component is called it crashes.

```bash
Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager.

This error is located at:
    in RNDateTimePicker (at datetimepicker.ios.js:81)
    in RCTView (at View.js:45)
    in View (at datetimepicker.ios.js:80)
    in Picker (at DatePicker.js:38)
    in RCTView (at View.js:45)
    in View (at DatePicker.js:31)
    in DatePicker (at HomeScreen.js:18)
    in RCTScrollContentView (at ScrollView.js:976)
    in RCTScrollView (at ScrollView.js:1115)
    in ScrollView (at HomeScreen.js:14)
    in RCTView (at View.js:45)
    in View (at HomeScreen.js:13)
    in HomeScreen (at SceneView.js:9)
    in SceneView (at DrawerView.js:149)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:20)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:16)
    in ResourceSavingScene (at DrawerView.js:148)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at DrawerView.js:138)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at DrawerLayout.js:446)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at DrawerLayout.js:445)
    in PanGestureHandler (at DrawerLayout.js:501)
    in DrawerLayout (at DrawerView.js:165)
    in DrawerView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at App.js:38)
    in ViewManagerAdapter_ExpoLinearGradient (at NativeViewManagerAdapter.js:49)
    in ForwardRef(Adapter<ExpoLinearGradient>) (at NativeLinearGradient.ios.js:5)
    in NativeLinearGradient (at LinearGradient.js:12)
    in LinearGradient (at App.js:37)
    in Provider (at App.js:36)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at createTabNavigator.js:39)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:37)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.js:26)
    in ResourceSavingScene (at createBottomTabNavigator.js:121)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at createBottomTabNavigator.js:111)
    in RCTView (at View.js:45)
    in View (at createBottomTabNavigator.js:110)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:61)
    in Navigator (at createAppContainer.js:429)
    in NavigationContainer (at App.js:38)
    in ViewManagerAdapter_ExpoLinearGradient (at NativeViewManagerAdapter.js:49)
    in ForwardRef(Adapter<ExpoLinearGradient>) (at NativeLinearGradient.ios.js:5)
    in NativeLinearGradient (at LinearGradient.js:12)
    in LinearGradient (at App.js:37)
    in Provider (at App.js:36)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at App.js:38)
    in ViewManagerAdapter_ExpoLinearGradient (at NativeViewManagerAdapter.js:49)
    in ForwardRef(Adapter<ExpoLinearGradient>) (at NativeLinearGradient.ios.js:5)
    in NativeLinearGradient (at LinearGradient.js:12)
    in LinearGradient (at App.js:37)
    in Provider (at App.js:36)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
- node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:29:4 in getNativeComponentAttributes
- node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:104:25 in get
- ... 18 more stack frames from framework internals


```

Library version: 1.0.0

## Steps To Reproduce

1. npm install --save @react-native-community/datetimepicker
2. expo start

Describe what you expected to happen:
1. For a button to appear where I could press and open the date picker

**Comment by adam-s** [comment] 2019-07-29 19:46
This package does not work with React Native .60

**Comment by denistsoi** [comment] 2019-07-29 19:48
Seems sort of buggy but going into `src/ios` and running `pod install` might find the dependancy.

> https://github.com/react-native-community/react-native-datetimepicker#manual-installation

**Comment by Swaagie** [comment] 2019-07-30 10:49
Thank your for reporting. I'm currently working on doing a full update to support `0.60`, I'll make sure to verify that it works as expected. The work in progress can be found here https://github.com/react-native-community/react-native-datetimepicker/pull/13

That said I did notice the reference to `expo`
> 2. expo start

I don't think expo by default supports native modules other than a set of modules from React Native itself and a selection of handpicked native API's.

**Comment by LucasLpr** [comment] 2019-08-07 16:14
Same issue :  "react-native": "0.59.8"

**Comment by Swaagie** [comment] 2019-08-13 08:28
@dmargu @adam-s  I've just published `@react-native-community/datetimepicker@2.0.0` which works against React Native 0.60, let me know if that resolves your build or runtime issues.

**Comment by umutcetinkaya** [comment] 2019-08-21 09:42
The same problem continues at 0.60

**Comment by zubjorge** [comment] 2019-08-21 22:51
@Swaagie is there anything different we need to do on version 2.0.0 to work  with RN 60? https://github.com/react-native-community/react-native-datetimepicker#manual-installation
I'm not able to build it, it looks it has something to do with the use_frameworks! 
https://github.com/facebook/react-native/issues/25349

**Comment by mrcl3an** [comment] 2019-08-28 23:56
This combination is also not working:

`
"@react-native-community/datetimepicker": "^2.0.0"
"react": "^16.8.6"
"react-native":` "^0.60.5"
`

Same error as the original poster when building on iOS

**Comment by evrimfeyyaz** [comment] 2019-09-11 12:10
@mrcl3an Did you try doing `pod install` and restarting the Metro Bundler?

**Comment by rendongsc** [comment] 2019-09-17 09:17
I am using expo 34.0.1 and I have encountered this problem.
```
  "expo": "^34.0.1"
```
```
React-native link
Expo install @react-native-community/datetimepicker
```
Have tried, still have problems

**Comment by vincentzierigen** [comment] 2019-09-23 23:00
I have the same problem, are there any solutions?

**Comment by mezhik91** [comment] 2019-09-24 19:28
expo 35.0.0 - same issue

**Comment by Nnoerregaard** [comment] 2019-09-25 10:29
I might be mistaken, but if you are using a managed expo workflow it seems this package will not work because expo does not support native modules and this package is a native module
https://docs.expo.io/versions/latest/introduction/faq/ (search for "native modules")

**Comment by mezhik91** [comment] 2019-09-25 18:19
@Nnoerregaard I am using a bare workflow which supports native modules [https://docs.expo.io/versions/v35.0.0/bare/exploring-bare-workflow/#adding-your-own-custom-native-code](https://docs.expo.io). So the issue is with something else :(

**Comment by yash1511** [comment] 2019-10-16 13:32
> @dmargu @adam-s I've just published `@react-native-community/datetimepicker@2.0.0` which works against React Native 0.60, let me know if that resolves your build or runtime issues.
I'm still getting the same error, but only on ios and not on android.
Library version `@react-native-community/datetimepicker@2.1.0`
Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

**Comment by yash1511** [comment] 2019-10-16 13:34
> @Swaagie @dmargu @adam-s I've just published `@react-native-community/datetimepicker@2.0.0` which works against React Native 0.60, let me know if that resolves your build or runtime issues.

I'm still getting the same error, but only on ios and not on android.
Library version @react-native-community/datetimepicker@2.1.0
Invariant Violation: requireNativeComponent: "RNDateTimePicker" was not found in the UIManager

**Comment by redBaron23** [comment] 2019-10-19 02:59
I've this:

Invariant Violation: Invariant Violation: requireNativeComponent: "DatePickerManager" was not found in the UIManager.
- node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:29:4 in getNativeComponentAttributes
- node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:104:25 in get
- ... 18 more stack frames from framework internals

**Comment by avtarnanrey** [comment] 2019-10-19 23:24
Any solutions for this?

React Native: 0.61.2
@react-native-community/datetimepicker: 2.1.0

**Comment by SallarBhutto** [comment] 2019-10-24 14:29
Adding 
pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec' in podfile solved it. 

 "react-native": "0.61.2",
 "@react-native-community/datetimepicker": "^2.1.0",
"react-native-modal-datetime-picker": "8.x.x",

**Comment by tsapeta** [comment] 2019-10-29 09:39
Yeah, adding `RNDateTimePicker` to the Podfile or using an autolink mechanism from react-native should solve this problem. Also, I've just merged https://github.com/expo/expo/pull/6087 so this native module will be a part of the next Expo SDK (36) so you will be able to use it in managed workflow as well 🎉

**Comment by leonardomarciano** [comment] 2019-11-11 13:40
Same error, on React-native 0.60.5.

Only in iOS.

The podfile hotfix does't works here.

**Comment by joelrorseth** [comment] 2019-11-24 18:12
Using react-native link and installing pods fixed this issue for me, on RN 0.60.3. Not sure why this section was removed from readme.

`react-native link @react-native-community/datetimepicker && cd ios && pod install`

**Comment by rzdev** [comment] 2019-12-11 17:00
@avtarnanrey 

React Native: 0.61.2
@react-native-community/datetimepicker: 2.1.0

- install (npm install / yarn install)
- cd ios
- pod install

*no need to link

works for me

**Comment by ermarin** [comment] 2019-12-17 22:49
Doesn't work

**Comment by leecommamichael** [comment] 2019-12-19 23:34
Strangely, this DOES work for me on RN 0.61.2 both iOS and Android work. I did nothing to manually install it. I did not edit Main.java, I did not change any gradle settings, I did not add anything to pod file.

**Comment by ermarin** [comment] 2019-12-20 20:30
> Strangely, this DOES work for me on RN 0.61.2 both iOS and Android work. I did nothing to manually install it. I did not edit Main.java, I did not change any gradle settings, I did not add anything to pod file.

Then only install with npm?

**Comment by leecommamichael** [comment] 2019-12-20 22:58
> > Strangely, this DOES work for me on RN 0.61.2 both iOS and Android work. I did nothing to manually install it. I did not edit Main.java, I did not change any gradle settings, I did not add anything to pod file.
> 
> Then only install with npm? Because this is not possible, in the documentation say's add in podfile, install pod, add in gradle... I don't understand

Yeah, just let autolinking take care of you I suppose.

**Comment by jefelewis** [comment] 2020-01-23 19:26
Was anyone able to get this to work?

I'm building an NPM Package and it works when running in the iOS simulator, but when I install the package through npm and import the component, the error occurs when I click on the picker. **My component renders, but it throws the error as soon as I click on it to bring up the picker.**

Not sure if it is a podfile issue, linking issue, or something else I'm missing. I'm on react-native 0.61.5, but I'm importing the RNDatepicker in the podfile.

[Invariant Violation: View config not found for name RNDateTimePicke](https://github.com/react-native-community/react-native-datetimepicker/issues/91)

Then this weird thing where I get a different error if I add `<SafeAreaView style={{ display: 'flex', flex: 1 }}>` to the container the NPM Package component is housed in.

[Invariant Violation: requireComponent: "RNDateTimePicker" was not found in the UIManager"](https://github.com/react-native-community/react-native-datetimepicker/issues/91#issuecomment-577463813)

**Comment by usman1579** [comment] 2020-02-05 09:00
ANY SOLUTION??

**Comment by DanielWahl** [comment] 2020-02-05 09:05
Mine now works fine after I updated my Expo SDK to 36.0.0.

**Comment by vonovak** [comment] 2020-02-05 09:22
I'm closing this because

- there is no runnable reproduction
- it's not clear whether the issue pertains to expo / vanilla RN
- not clear what version of expo / RN is affected

@usman1579 please open a new issue with a runnable reproduction if the problem persists. Thanks.

**Closed by vonovak** 2020-02-05 09:22 UTC
Labels: bug
